### ISSUE TITLE
How to deal with inverted tx from VMC

### ISSUE THREAD

**Issue by note5** [Nauman3S/MQTTToMDBBridge#1]
Hi,

I would like to know if your vending machine controller has inverted TX? if so how does this code handle it?

I start the vending machine the I see reseting  on the terminal until I get error

Error: invalid checksum [SETUP]
data[5]: 0x000013 ;;checksum-calc: 0x000013
ACK00
data[5]: 0x000010 ;;checksum-calc: 0x000010

What could be causing this?

**Comment by Nauman3S** [comment]
@note5 Hi, this is not a well-maintained project and may have some outdated information. There are a couple of solutions to the inverted TX. The easiest one is to use a physical hex inverter or a buffer IC with an inverted output. 

The software-based approach could be:

1) Try inverting hex values in the firmware
`    unsigned int hex;
     int inverted_hex=~hex;
`
and use `inverted_hex` everywhere.

2) Use a logic analyzer, record the TX, and RX values of a session and modify the firmware accordingly. This is the recommended approach as it allows fast debugging.

**Comment by note5** [comment]
Thanks for the reply, I am am using a Godrej Tea vending dispenser. In the circuit it shows mdb as follows; 

![image](https://github.com/Nauman3S/MQTTToMDBBridge/assets/17497080/a86f53b7-7124-4d47-aec0-4ae56f9d5c55)

Will this change te circuit? I see the NAMA protocol is still at version 4.2 meaning the code is still valid

**Comment by Nauman3S** [comment]
For a hardware-wise approach, you would need to put a hex inverter on the TX line with ground common to the MCU.

**Comment by note5** [comment]
If I am getting this correctly, does it mean I pass the mdb tx through another  inverter if the 7414  (I have already replicated your fritzing circuit)

So instead of one inversions as currently is I add the output of the tx through another inverter before feeding it to the atmega2560's rx1 pin?
![image](https://github.com/Nauman3S/MQTTToMDBBridge/assets/17497080/fba3c221-9363-41bd-a2d8-c7c68a85a3be)

**Comment by Nauman3S** [comment]
No, there will only be one hex inverter. You can simplify the circuit by removing the brown wires. The circuit should invert the signal only once. The circuit above is a bit confusing so it's better to ignore how hex inverter is placed in the circuit.

**Comment by note5** [comment]
How would it look like? I am  a bit lost
